Repository yunsly/SpaceNote, pull requests merged in 2025-06, with the labels that each got.

#12 🔧 Config. .github/PULL_REQUEST_TEMPLATE.md 파일 추가 + 메인 연결
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  SpaceNote.xcodeproj/project.pbxproj
  SpaceNote.xcodeproj/project.xcworkspace/xcuserdata/yunsly.xcuserdatad/UserInterfaceState.xcuserstate
  SpaceNote/Assets.xcassets/SpaceBackground.imageset/Contents.json
  SpaceNote/Assets.xcassets/SpaceBackground.imageset/background-1.png
  SpaceNote/Components/GlowingStar.swift
  SpaceNote/Managers/NavigationManager.swift
  SpaceNote/Managers/Route.swift
  SpaceNote/Managers/ShakeDetector.swift
  SpaceNote/Models/.gitkeep
  SpaceNote/Models/StarPoint.swift
  SpaceNote/SpaceNoteApp.swift
  SpaceNote/ViewModels/StarPointViewModel.swift
  SpaceNote/Views/MainSpaceView.swift
Labels: task

#16 🐛 Fix. 별자리 연결 시 동일 별 중복 추가 오류 해결
  SpaceNote/SpaceNoteApp.swift
  SpaceNote/ViewModels/StarPointViewModel.swift
  SpaceNote/Views/MainSpaceView.swift
Labels: bug

#20 💄Design. #18 editbutton UI fix
  SpaceNote/Views/BottomButtonBarView.swift
  SpaceNote/Views/MainSpaceView.swift
Labels: UI/UX

#24 🐛 Fix. 별자리 연결 및 이동 기능 복구를 위한 좌표 계산 방식 수정
  SpaceNote.xcodeproj/project.xcworkspace/xcuserdata/yunsly.xcuserdatad/UserInterfaceState.xcuserstate
  SpaceNote/Components/GlowingStar.swift
  SpaceNote/Models/StarPoint.swift
  SpaceNote/ViewModels/StarPointViewModel.swift
  SpaceNote/Views/BottomButtonBarView.swift
  SpaceNote/Views/ConstellationView.swift
  SpaceNote/Views/ExpandableSpaceView.swift
  SpaceNote/Views/MainSpaceView.swift
  SpaceNote/Views/test.swift
Labels: bug
